[package]
name = "ddex_parser_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.4", default-features = false, features = ['std'] }
core = { path = "../../core" }
ddex_schema = { path = "../../../ddex_schema/ddex_schema"}

